// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PaderbornUniversity.SILab.Hip.Auth.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using PaderbornUniversity.SILab;
    using PaderbornUniversity.SILab.Hip;
    using PaderbornUniversity.SILab.Hip.Auth;
    using System.Linq;

    public partial class NotificationModel
    {
        /// <summary>
        /// Initializes a new instance of the NotificationModel class.
        /// </summary>
        public NotificationModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NotificationModel class.
        /// </summary>
        public NotificationModel(string recipient, string subject, string topic, string updater, System.DateTime date, string action)
        {
            Recipient = recipient;
            Subject = subject;
            Topic = topic;
            Updater = updater;
            Date = date;
            Action = action;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recipient")]
        public string Recipient { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subject")]
        public string Subject { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "topic")]
        public string Topic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updater")]
        public string Updater { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public System.DateTime Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "action")]
        public string Action { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Recipient == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Recipient");
            }
            if (Subject == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Subject");
            }
            if (Topic == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Topic");
            }
            if (Updater == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Updater");
            }
            if (Action == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Action");
            }
        }
    }
}
